services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "spotiparty"
      POSTGRES_PASSWORD: "123mudar"
      POSTGRES_DB: "spotiparty-db"
    ports:
      - "5432:5432"
    volumes:
      - /spotiparty-data:/var/lib/postgresql/data